### ISSUE TITLE
Error with src/index file

### ISSUE THREAD

**Issue by terencestone** [rauliyohmc/react-native-offline-utils#13]
Would really like to use your library but got this error right off the bat:

![screen shot 2017-06-01 at 5 00 45 pm](https://cloud.githubusercontent.com/assets/19293584/26700618/042b510e-46ec-11e7-9f76-08dc325bd1f9.png)

**Comment by rauliyohmc** [comment]
Could you share your `.babelrc` file? The library exports the modules using ES6 syntax, so you should add [babel-preset-react-native-stage-0](https://github.com/skevy/babel-preset-react-native-stage-0) preset or alternatively [babel-plugin-syntax-export-extensions](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-export-extensions) plugin to your `.babelrc` config

**Comment by terencestone** [comment]
Hey thanks for your response. This is all that's in my babelrc file: 

{
"presets": ["react-native"]
}

And installing either of those libraries didn't change anything.

**Comment by rauliyohmc** [comment]
I released a new version that should fix it. You should be able to use the library without the need of any extra babel plugin/preset. Let me know if you have further issues

**Comment by terencestone** [comment]
Thank you!
