### ISSUE TITLE
Documentation - babel plugin

### ISSUE THREAD

**Issue by padupuy** [rauliyohmc/react-native-offline-utils#7]
Hi,
To use your lib, i had to use `babel-plugin-syntax-export-extensions` and add it to my `.babelrc` file.

```
{
    "presets": [
        "react-native"
    ],
    "plugins": [
        "syntax-export-extensions"
    ]
}
```

**Comment by rauliyohmc** [comment]
Hi,
Thanks for reporting that! I updated the documentation in order to reflect that babel dependency
