### ISSUE TITLE
No reducer provided for key "network"

### ISSUE THREAD

**Issue by padupuy** [rauliyohmc/react-native-offline-utils#8]
It seems there is a problem with the way you export your module or the way I use it ..
when I try to import the reducer, i've got this error
`import { reducer as network } from 'react-native-offline-utils';`
-> `ExceptionsManager.js:71 No reducer provided for key "network"`

**Comment by rauliyohmc** [comment]
Could you please paste your code where you initialise your root reducer in your redux store?

**Comment by rauliyohmc** [comment]
You are right, it's needed a babel preset/plugin to correctly parse the ES2015 syntax used for exporting the modules. I [updated the docs](https://github.com/rauliyohmc/react-native-offline-utils/commit/a01b4c071b1d3aedf6125524529fd242b117c8d3) to reflect that.
